### ISSUE TITLE
refine on click

### ISSUE THREAD

**Issue by yaca29** [opendatasoft/ods-widgets#101]
Hi,

I'd like to reproduce the action on a keyword of a dataset/catalog  (or a value of one another field) in the explore page on ODS portal : When I click on the value, i'd like to refine the context. But i didn't find the way to do that !

I think it's possible with the refineOnClick, but i'm not sure. 

Is it possible to do that with the widget ? how ?

Thanks in advance,

Yann

**Comment by jmorel** [comment]
Hello Yann,

refineOnClick isn't what you're looking for since it doesn't work in and of itself. It's designed to be included within your own directives, where you'd require the presence of the refineOnClickController.

For keywords, what we do is use the `toggleRefine()` property of the context as such:
```html
<button ng-click="mycontext.toggleRefine('keyword', keyword)" ng-bind="keyword"></button
```

I hope this helps.

**Comment by yaca29** [comment]
Hi Jérémy,
I tried, but it doesn't work for me. I replace mycontext by catalog, but nothing happen. 
Did i miss something ?
Kindly,
Yann
my code :

<div class="container-fluid">
    <ods-catalog-context context="catalog">
        <ods-filter-summary
           context="catalog" clear-all-button="false">
        </ods-filter-summary>
        <ods-result-enumerator context="catalog" max="5">
            {{item.metas.title}}
            <br>
                        <span ng-repeat="keyword in item.metas.keyword">
                            <button ng-click="catalog.toggleRefine('keyword', keyword)" ng-bind="keyword"></button>
                        </span>
            <br>
        </ods-result-enumerator>
    </ods-catalog-context>
</div>

-> http://data.enseignementsup-recherche.gouv.fr/pages/test98/

**Comment by Amli** [comment]
Hi Yann,

The ods-result-enumerator hides the original context. In fact it creates a new scope for himself and stores the given context in scope.context.
So when you are inside the ods-result-enumerator, you must use:

`<button ng-click="context.toggleRefine('keyword', keyword)" ng-bind="keyword"></button>`

It should be working fine as is.

**Comment by yaca29** [comment]
Hi Emmanuel,
Thanks, it's working great.
Kindly
Yann
