### ISSUE TITLE
any example of getQueryStringURL

### ISSUE THREAD

**Issue by yaca29** [opendatasoft/ods-widgets#103]
Hi,

Can you give me an example that use the property getQueryStringURL from the odsDatasetContext's widget ?

Kindly,

Yann

**Comment by richterb** [comment]
Here's an example of getQueryStringURL and getDownloadURL: http://plnkr.co/edit/9ZOjwb5A4PTKuKwaS74T?p=preview

**Comment by yaca29** [comment]
Hi again,
Thanks for this example. 
Yann
