### ISSUE TITLE
ods-map don't display all items of my dataset

### ISSUE THREAD

**Issue by yaca29** [opendatasoft/ods-widgets#104]
Hi,

I've a issue with a dataset with a item in Antarctic. The map is cropped, and don't show most of the items.

These are the coordinates on my dataset :

géocode
-75.1,123.3329
 48.260250, 11.670878
 51.41956, -0.95077
19.825277, -155.468768
-23.272354, 16.506801
43.1222, 5.93
43.340036, 5.435627
43.538335, 10.442709
43.631389, 10.505000
43.699177, 5.746887
44.657846, -0.807386
44.805949, -0.592167
45.187778, 5.726945
45.193622, 5.760902
45.204086, 5.701727
45.206638, 5.693662
45.208491, 5.690057
45.780745, 4.863521
45.781272, 4.867420
46.23335, 6.083323
47.381500, 2.194932
47.828314, 1.914012
47.9108329, 1.9157977
48.582949, 7.766742
48.698658, 2.179426
48.701844, 2.134078
48.711922,2.146156
48.719124, 2.221294
48.828068, 2.344808
48.836173, 2.371599
48.844568, 2.344068
48.845017, 2.285317
48.855532, 2.331288
48.856578, 2.351828
49.182863, -0.370679
49.189006, -0.363995
49.2115536, -0.3600668
49.388563, 8.707659
49.931389,8.679167
53.590884, 9.828812
55.708244, 13.219903

**Comment by richterb** [comment]
Hello,

The one problem we can find is that the map's initial position can't show all the items at once. There is a maximum level of zoom of 2 per default on maps to avoid weird effects, and unfortunately if the map is not big enough it may not show the entire world at once. You can try to add `min-zoom="1"` on the `ods-map` tag to make it able to unzoom more, and it may fix your problem.

**Comment by yaca29** [comment]
hi Benoit,
great, it works !
thanks again
