### ISSUE TITLE
Question about Opendatasoft API <FACET> filter

### ISSUE THREAD

**Issue by GrondinDam** [opendatasoft/ods-widgets#108]
Hello,

I'm Grondin Damien. I actually work on a project named Communecter. Visible at www.communecter.org

In my work, I would like to interact with multiple API, and Opendatasoft's API in particular.

I have some questions about the filter we can do with the API. (with refine.<FACET>)

I would like to know if it is possible to put multiple filter with the same facet but with an OR operator.

I saw that it is possible but with the AND operator (element with facetA equal to filter1 AND filter2) but I would like to do the same thing but with the OR operator (element with facetA equal to filter1 OR filter2).

```
Ex:
- refine.<facetA>=filter1 & refine.<facetA>=filter2  (=> Possible )
- refine.<facetA>=filter1 || refine.<facetA>=filter2  (=> Impossible )
```

Sorry for my frenchy bad english. Tell me if I am too imcomprehensible.

Kindly.

**Comment by fpassaniti** [comment]
Hello,

Filters can be refined exclusively by default but you can also activate the disjunctive mode. it means that you'll be able to refine on several values and it will refine like in your exemple, valueA OR valueB OR valueC etc...


to try it, have a look to this dataset :

https://discovery.opendatasoft.com/explore/dataset/us-hospitals/

City filter is exclusive (default behavior)
https://discovery.opendatasoft.com/explore/dataset/us-hospitals/?refine.city=Houston

If you add &disjunctive.city=true it will switch to the disjunctive (OR) mode and allows you to select several values :

https://discovery.opendatasoft.com/explore/dataset/us-hospitals/?refine.city=Houston&refine.city=Dallas&disjunctive.city=true

Have fun ;)

Fred

**Comment by GrondinDam** [comment]
Exactly what I needed ! I love you Fred :)

I didn't saw this feature in the doc here : 
https://data.opendatasoft.com/api/v1/documentation

But I just saw it here : 
https://docs.opendatasoft.com/en/using_api/v1/

Thank's again.

Kindly.
