### ISSUE TITLE
ods-dataset-context can't do alphabetical sort using 'parameters' setting

### ISSUE THREAD

**Issue by scMarth** [opendatasoft/ods-widgets#112]
`<ods-dataset-context context="tree" tree-dataset="trees" tree-parameters="{'sort': 'field'}"></ods-dataset-context>`

It seems that the above will work if 'field' contains integer or decimal types, but will not alphabetically sort strings.

**Comment by fpassaniti** [comment]
Hi @scMarth ,

It do works if your field is sortable. Integers and decimals are by default, dates also.
String fields are sortable if set as facet, or explicitly set as sortable. 

If not, you should have an error in your console, the API query should return an error explaining that the field is not sortable.

**Comment by scMarth** [comment]
Thanks I got it to work by explicitly setting the field as sortable.

It seems that text fields are not sortable even if you set them as a facet. Originally, I had the field set as a facet it wasn't set to sortable, and I was getting a GET error code 400 in my console, and the results would not show (it only shows the loading animation for that widget). It seems that you must explicitly set them as sortable.
