### ISSUE TITLE
Unable to show image from record

### ISSUE THREAD

**Issue by Eliawyn** [opendatasoft/ods-widgets#118]
Hi,

I have a dataset **XXX** in my domain.opendatasoft.com that contains localisation and an image file per record.
I have a custom html file on my PC that retrieve information from ODS.

I'm able to show only one record when I use the `ods-map` tag : 
```html
<ods-dataset-context    context="mycontext"
                        mycontext-domain="domain.opendatasoft.com"
                        mycontext-apikey="the-real-apikey"
                        mycontext-dataset="XXX"
                        mycontext-parameters="{'q':'column_1:37618'}">
    <ods-text-search context="mycontext"></ods-text-search>
    <ods-map    context="mycontext" 
                toolbar-fullscreen="false"
                toolbar-drawing="false"
                toolbar-geolocation="false">
    </ods-map>
</ods-dataset-context>
```

But the problem resides in the tooltip where the image is not present below the field **Fichier**:
![image](https://user-images.githubusercontent.com/16443246/44209143-d8be0980-a162-11e8-8053-a0b207fd40e1.png)

On OpenDataSoft website, if I go in datasets > map, the image is shown as wanted.

I tried to manually specify to show the image in tooltip, but here I have an error that says `Error: image is undefined
render@https://opendatasoft.github.io/ods-widgets/dist/ods-widgets.js:25105:1 (...)`:
```html
<ods-dataset-context    context="mycontext"
                        mycontext-domain="domain.opendatasoft.com"
                        mycontext-apikey="the-real-apikey"
                        mycontext-dataset="XXX"
                        mycontext-parameters="{'q':'column_1:37618'}">
    <ods-text-search context="mycontext"></ods-text-search>
    <ods-map    toolbar-fullscreen="false"
                toolbar-drawing="false"
                toolbar-geolocation="false">
        <ods-map-layer context="mycontext">
            <div><strong>Type : </strong>{{record.fields.natur_desc}}</div>
            <div><strong>Numero : </strong>{{record.fields.numero}}</div>
            <div><strong>Rue : </strong>{{record.fields.rue_nom}}</div>
            <div><strong>Code postal : </strong>{{record.fields.codepostal}}</div>
            <div><strong>Ville : </strong>{{record.fields.commu_nom}}</div>
            <!-- HERE -->
            <ods-record-image record="record"></ods-record-image>
        </ods-map-layer>
    </ods-map>
</ods-dataset-context>
```

Is there a way to get this image ?
I also use the api to get data. If I could get this image with the api is fine too.

Thank you

**Comment by Eliawyn** [comment]
Thanks for the quick response.

Sadly, it doesn't work with the domain-url either.
I still have the same issue.

The full error is the following: 
```
Error: image is undefined
render@https://opendatasoft.github.io/ods-widgets/dist/ods-widgets.js:25105:1
link/<@https://opendatasoft.github.io/ods-widgets/dist/ods-widgets.js:25118:21
$digest@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.7/angular.min.js:130:481
$apply@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.7/angular.min.js:133:510
h@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.7/angular.min.js:87:374
K@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.7/angular.min.js:91:499
Sf/</z.onload@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.7/angular.min.js:93:37
```

**Comment by richterb** [comment]
Can you add the `field` attribute to indicate the name of the field that should contain the image and see if that fixes your issue?
```html
<ods-record-image field="myimage" record="record" domain-url="https://domain.opendatasoft.com"></ods-record-image>
```

**Comment by Eliawyn** [comment]
Yes, thank you! It does work now.

Thanks for your time and have a great day.

**Comment by Eliawyn** [comment]
I reopen the issue because I have a new related problem.

I've tested the working solution on firefox, it works well.
But when I try on Google Chrome, the image is not rendered : 
![screenshot_4](https://user-images.githubusercontent.com/16443246/44339052-40849500-a480-11e8-8269-921e718d11be.png)

In the browser's console, it's an **error 401** when I open the tooltip that appears.

Do you have knowledge of this issue ?

**Comment by vbarbaresi** [comment]
A guess would be that you are doing cross-domain requests on private datasets, and you had a valid cookie on Firefox on this other domain.
If the widget code is not public, you could use an apikey. Or manually log on the other domain with Chrome before displaying the map.

**Comment by Eliawyn** [comment]
Thanks for the response.

I already use an apikey (if you see my first message in this issue, you'll see in the code) which is related to a private domain.

The fix you propose where I log on the other domain with Chrome should be a problem for what I want to do.
I'm building a web page where people can login and see the map. If the apikey is there, anyone could view the map and image, no ?

**Comment by vbarbaresi** [comment]
I agree, I was just proposing an explanation on the why it doesn't work on Chrome, while it worked on Firefox.
I'm investigating into why the API key is not forwarded to the tooltip call in your case

**Comment by vbarbaresi** [comment]
There is indeed an issue with `ods-record-image`: it doesn't support using the context-apikey for now.
Sorry about the inconvenience

As a workaround you can manually build the URL to the image with an APIKey like this:
```html
<img src="{{ context.domainUrl + '/explore/dataset/' + context.dataset.datasetid + '/files/' + record.fields.myimage.id + '/300/' + '?apikey=' + context.apikey }}"/>
```
(Replace `myimage` by the name of the field containing the image)

**Comment by Eliawyn** [comment]
@vbarbaresi, thank you for the solution.

It's working with the image. I'm perfectly fine with that workaround!

Have a nice day

**Comment by vbarbaresi** [comment]
Thanks 👌
