### ISSUE TITLE
Linking context

### ISSUE THREAD

**Issue by bendem** [opendatasoft/ods-widgets#129]
Hi, we are looking for a way to link contexts so we can display parts of a dataset differently on a map while using the default page context (ctx) used by the sidebar filters.

We tried a few things, it looked like it should be possible using `parameters-from-context`, but that supposedly overrides the local parameters instead of merging them with the source context (also, it's apparently broken? https://github.com/opendatasoft/ods-widgets/issues/74). I've found https://github.com/opendatasoft/ods-widgets/blob/ef925879f1c050f9a435bb45107afd2a138fc6a7/src/directives/dataset-context.js#L84 which said context-refine was being considered but it was a long time ago.

What we have: a list of records with two different types
What we want: display those records with different pictos on a map, while still applying the filters from `ctx` (it's possible for colors using `color-categories` on `odsMapLayer`)
What we tried and didn't work: creating two contexts using `-parameters="{'refine.type':'B2_'}"`

```html
<ods-dataset-context
                     context="velocitepanneauxb22,velocitepanneauxb23"
                     velocitepanneauxb22-dataset="velocite-panneaux-b22-et-b23"
                     velocitepanneauxb22-parameters="{'refine.type':'B22'}"
                     velocitepanneauxb23-dataset="velocite-panneaux-b22-et-b23"
                     velocitepanneauxb23-parameters="{'refine.type':'B23'}">
    <ods-map scroll-wheel-zoom="true"
             display-control="true"
             search-box="true"
             toolbar-fullscreen="true"
             toolbar-geolocation="true">
        <ods-map-layer-group>
            <ods-map-layer context="velocitepanneauxb22"
                           color="#C32D1C"
                           picto="ods-right"
                           show-marker="true"
                           display="auto"
                           shape-opacity="0.5"
                           point-opacity="1"
                           caption-picto-icon="ods-right"
                           caption-picto-color="#BA0129"
                           title="Panneaux b22"
                           size="4" size-min="3" size-max="5" size-function="linear"></ods-map-layer>
        </ods-map-layer-group>
        <ods-map-layer-group>
            <ods-map-layer context="velocitepanneauxb23"
                           color="#F98B44"
                           picto="ods-top"
                           show-marker="true"
                           display="auto"
                           shape-opacity="0.5"
                           point-opacity="1"
                           caption-picto-icon="ods-top"
                           caption-picto-color="#F98B44"
                           title="Panneaux b23"
                           size="4" size-min="3" size-max="5" size-function="linear"></ods-map-layer>
        </ods-map-layer-group>
    </ods-map>
</ods-dataset-context>
```

**Comment by wmai** [comment]
Hi, if I'm not mistaken, it seems that the integration you want to do would be inside a custom view linked to your domain. If this is the case, please contact our support so we can investigate your problem in the context of your domain/dataset.

**Comment by bendem** [comment]
The problem didn't seem at all specific to our domain, that's why I asked here. Have sent a mail to the support, will update here if a solution is provided.
