### ISSUE TITLE
odsMap: in shape+remote  mode, ability to display the content of a field on hover

### ISSUE THREAD

**Issue by richterb** [opendatasoft/ods-widgets#40]
Current, when in shape mode, hovering a shape displays the aggregated value. When in remote join mode, It would be nice to be able to specify a field in the joined shape to display.
For example, if I joined on a dataset of shapes of countries, I may want to display the country name.

**Comment by richterb** [comment]
```html
<ods-map>
    <ods-map-layer hover-field="mykey" context="local" join-context="remote" local-key="mykey" remote-key="mykey" display="aggregation" expression="value" function="AVG">value</ods-map-layer>
</ods-map>
```

**Comment by itkg-ttourneur** [comment]
@richterb 
Bonjour, 
auriez-vous un exemple complet de l'utilisation du join-context que vous utilisez ci-dessus?
Nous aimerions faire une "jointure" entre deux jeux de données pour afficher le résultat sur une map.
Merci d'avance.

**Comment by richterb** [comment]
Bonjour,

Voici un exemple complet en ligne : http://plnkr.co/edit/wawM1rLb9SqL1qeTycVI?p=preview

L'idée est d'utiliser comme contexte original un jeu de donnée contenant les données numériques à aggréger, et d'utiliser comme contexte de "jointure" (join-context) un jeu de données contenant les formes géographiques à utiliser ; puis d'indiquer la clé permettant la correspondance.
Les 2 contextes doivent être issues du même "domaine" (le même portail).

Dans l'exemple plus haut, on utilise comme contexte de jointure la liste de référence des départements français avec leurs contours.

A noter qu'il est souvent bien plus simple de faire cette jointure en "amont" dans le jeu de données, mais évidemment cela suppose d'être la personne qui a publié le jeu de données à l'origine ;)
