### ISSUE TITLE
odsFacet: the valuesearch "x" button to delete doesn't show if you search for "f"

### ISSUE THREAD

**Issue by richterb** [opendatasoft/ods-widgets#43]
Oddly enough, it works for every other character it seems.

**Comment by Amli** [comment]
nice angular bug: angular/angular.js/issues/1229
fixed in 1.3

**Comment by richterb** [comment]
Ahah, nice catch.
So we just need to add `!!` before the expression in `ng-show` I guess. The original submitter used this to fix it on his app.

**Comment by Amli** [comment]
yep, that's the plan ;)
