### ISSUE TITLE
No fields in tooltip on map (CORS problem)

### ISSUE THREAD

**Issue by yaca29** [opendatasoft/ods-widgets#48]
Hi,

If the ods-widgets.js or ods-widgets.min.js file is on another domain, the tooltips are empty (no field) when i use the ods-map tag

The error on log is : 
XMLHttpRequest cannot load http://c.par-la.fr/ods/templates/geoscroller_tooltip.html. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://XXX.fr' is therefore not allowed access.

Is it possible to allow cross domain for this file ?

Kindly

Yann

**Comment by Amli** [comment]
Hi

yes CORS should be activated very soon.
Thanks for reporting

**Comment by richterb** [comment]
Although in that case, it is the server hosting the templates ("c.par-la.fr") that should allow CORS by sending the right headers. (if I'm understanding the situation correctly)

If you have trouble or can't configure it, I think we are probably going to remove the external templates very soon to fix the various situations where CORS is posing problems.

**Comment by yaca29** [comment]
indeed, it's work with a .htaccess

<IfModule mod_headers.c>
    Header set Access-Control-Allow-Origin http://XXX
    Header set Access-Control-Allow-Credentials true
</IfModule>

here is the result : http://www.enseignementsup-recherche.gouv.fr/cid20269/liste-des-universites-francaises.html 

thanks

**Comment by richterb** [comment]
No problem (nice page!)
