### ISSUE TITLE
parameter sort of directive odsFacets doesn't like french accents !

### ISSUE THREAD

**Issue by yaca29** [opendatasoft/ods-widgets#51]
like in that url : http://www.enseignementsup-recherche.gouv.fr/cid20269/liste-des-universites-francaises.html the facet display at the end of the list the values "Étranger" and "Île-de-France"

**Comment by richterb** [comment]
This is actually a limitation of OpenDataSoft's API, not a problem with the widget. But we think we can fix the API to fix this exact problem, hopefully in the coming days.

**Comment by richterb** [comment]
Alright, the API just got support for it, and your page now shows properly sorted regions :)

**Comment by yaca29** [comment]
You're so great, thanks a lot
