### ISSUE TITLE
export data from a context

### ISSUE THREAD

**Issue by yaca29** [opendatasoft/ods-widgets#55]
hi,

is there any solution to make a link to export the dataset in current context with facets values

to make an url like this
http://data.enseignementsup-recherche.gouv.fr/explore/dataset/fr-esr-insertion_professionnelle-master/download?format=xls&refine.annee=2011&refine.code_de_la_discipline=disc01&refine.academie=Besan%C3%A7on

thus, user can easily export data

kindly 

yann (again)

**Comment by richterb** [comment]
Not currently, but that's a good idea. I think we could have a method on the context that returns the current parameters as a querystring, and possibly another one that could return a download URL up to date with the active parameters. Then you'd be able to directly use them. I'll have a look next week

**Comment by yaca29** [comment]
thanks, have a nice week-end

**Comment by richterb** [comment]
Thank, yoo too :)

**Comment by richterb** [comment]
The new version now supports it:

```html
    <ods-dataset-context context="ctx" ctx-dataset="jcdecaux-bike-stations-data">
        <a ng-href="{{ctx.getDownloadURL()}}" target="_self">Download</a>
    </ods-dataset-context>
```

**Comment by yaca29** [comment]
thanks a lot for the new release
have a nice week-end
