### ISSUE TITLE
how to obtain extra_metas informations ?

### ISSUE THREAD

**Issue by yaca29** [opendatasoft/ods-widgets#56]
hi (again)

is it possible to show extra metas informations from a context, like processing_modified parameter ?

it's for showing the date of the last update of a dataset like this "Mise à jour des données : 13.01.2015"

kindly

yann

**Comment by richterb** [comment]
First, it is not advised to use this date, as it represents the last modification of the processing configuration on OpenDataSoft's platform (e.g. a processor has been added, or a new ressource). If the data source changes by itself, or if metadata is changed, this date won't change. It is usually advised to use the regular "modified" meta, but it only changes if the publisher decides so. We don't have a reliable date to indicate when the data itself has changed at all, although we want to add it in the future.

That being said, if you really want to use it, it should be possible directly using `CONTEXTNAME.dataset.extra_metas.processing.processing_modified`

For example (available as a sample here: http://plnkr.co/edit/liBWtqMQ2cvWeqUShmVK?p=preview)
```html
<ods-dataset-context context="public" public-domain="public.opendatasoft.com" public-dataset="repartition-de-la-reserve-parlementaire-en-2014">
  Last modification: {{public.dataset.extra_metas.processing.processing_modified}}, or nicely formatted {{public.dataset.extra_metas.processing.processing_modified|moment:'LLL'}}
</ods-dataset-context>
```

**Comment by yaca29** [comment]
thanks for the explanation and the solution
