### ISSUE TITLE
odsMap: color by specific values

### ISSUE THREAD

**Issue by richterb** [opendatasoft/ods-widgets#61]
Add a new coloring type by "values". Only active for modes that can retrieve record values.

``` html
<ods-map-layer context="myctx" display="raw" color-values="Red Team;#FF0000;Green Team;green"></ods-map-layer>
```

**Comment by kachroudi-Nedra** [comment]
Hi, it's corrected or no? i need to do the show raw with different color .
`      <ods-map-layer context="calaisheatdates" display="raw"  expression="pression" function="AVG"  color-values="blue;10;green;1500;red"></ods-map-layer>

`
how can i do this? 

Thanks for reply

**Comment by kachroudi-Nedra** [comment]
<ods-map-layer context="calaisheatdates" display="raw"  expression="pression" function="AVG"  color-values="blue;10;green;1500;red"></ods-map-layer>

**Comment by fpassaniti** [comment]
Try this : 

<ods-map-layer context="calaisheatdates" display="raw"  color-by-field="pression" color-ranges="blue;10;green;1500;red"></ods-map-layer>

**Comment by kachroudi-Nedra** [comment]
Thanks, it works but i want the AVG of pression and not just pression, how can i do this?

**Comment by richterb** [comment]
You need to use the "aggregation" display, set an expression and a function: the color will apply to the result of the aggregation, you don't need color-by-field anymore.

That would look like:
```
<ods-map-layer context="calaisheatdates" display="aggregation" function="AVG" expression="pression" color-ranges="blue;10;green;1500;red"></ods-map-layer>
```


A example on a public dataset:
```html
<ods-dataset-context  context="geoflardepartements2015" 
                     geoflardepartements2015-domain="public"
                     geoflardepartements2015-dataset="geoflar-departements-2015">
    <ods-map>
        <ods-map-layer context="geoflardepartements2015"
                       color-ranges="blue;500000;green;1000000;red"
                       function="AVG"
                       expression="x_chf_lieu"
                       display="aggregation"></ods-map-layer>
    </ods-map>
</ods-dataset-context>
```
