### ISSUE TITLE
odsTimescale overwrite the q parameters in contexts it touches

### ISSUE THREAD

**Issue by Amli** [opendatasoft/ods-widgets#63]
It should use a different parameter or concatenate with with existing value.

**Comment by richterb** [comment]
After thinking about it for a long while, the best solution in my opinion is to have this kind of widget set a parameter "q.something"; basically, when the widget uses the q parameter for something else than a query you'd display in a text search.

Then ODSAPI, at query time, can transform all the q.xxx into q (if a q already exists then it becomes an array). This has the good bonus that if the API supports q.xxxx one day, then we'll just have to remove 2 lines of code and everything will work even better.
