### ISSUE TITLE
Advanced maps tutorial seems broken

### ISSUE THREAD

**Issue by Aquassaut** [opendatasoft/ods-widgets#66]
In the [advanced maps tutorial](http://opendatasoft.github.io/ods-widgets/docs/#/tutorial/04advancedmap), in the bottom of the page, I get no page, and a bunch of stacktraces in the console, but mostly, I get this error, which seems very self-explanatory:

```Uncaught ReferenceError: jQuery is not defined```

**Comment by richterb** [comment]
The jQuery CDN seems down. It's probably going to get back soon (otherwise I think a lot of people are going to have a problem :)).

**Comment by richterb** [comment]
According to Twitter, it seems down since 4+ hours, and indeed, a lot of people are having a lot of problems.

**Comment by Aquassaut** [comment]
Ah, I see, wrong place wrong time :-) 
Closing.
