### ISSUE TITLE
labels of hierarchical facet don't appear 

### ISSUE THREAD

**Issue by yaca29** [opendatasoft/ods-widgets#90]
since release 1.0.0, there is a problem with odsFacet 

like in this example of the tutorial http://opendatasoft.github.io/ods-widgets/docs/#/api/ods-widgets.directive:odsFacets , where the label of the tags' facets doesn't appear on the left, but date facets works

in the dataset, the tags is define as hierarchical :
http://public.opendatasoft.com/explore/dataset/evenements-publics-cibul/?flg=fr&refine.tags=concert

can you fix it ? 

the facets of our page http://www.enseignementsup-recherche.gouv.fr/cid81783/carte-coordonnees-des-pepite.html work with an older version of the widgets, but the maps don't, since few days

**Comment by richterb** [comment]
There is an undocumented change with ODS-Widgets 1.0 (due to Angular 1.4 actually), which is that you have to wrap the custom display of your facet with a tag (like a span tag).

For example
```html
<ods-facet name="region" visible-items="33" sort="alphanum">{{category.name}}</ods-facet>
```

should now be:
```html
<ods-facet name="region" visible-items="33" sort="alphanum">
    <span>{{category.name}}</span>
</ods-facet>
```

The documentation suffers from this problem, we didn't update it yet.

**Comment by yaca29** [comment]
thanks for your answer
