### ISSUE TITLE
ods-chart-serie change the Label 

### ISSUE THREAD

**Issue by kachroudi-Nedra** [opendatasoft/ods-widgets#91]
Hi, 
The label-y doesn't work, how can i set the label?
       
         <ods-chart-serie label-y="Totale des places" expression-y="nombre" chart-type="pie" function-y="SUM" color="range-Accent">

Thanks

**Comment by Amli** [comment]
Hi,
I cannot reproduce the problem, could you provide a more complete failing example ?

here is a working example: http://plnkr.co/edit/TGV8Ht5TKi1f7XGJg5XZ

**Comment by kachroudi-Nedra** [comment]
thanks it works
