### ISSUE TITLE
 ods-timerange one date field

### ISSUE THREAD

**Issue by kachroudi-Nedra** [opendatasoft/ods-widgets#92]
Hi,

How can i add timerange for one date? not two dates, is that possible?
  <ods-timerange context="context" default-from="2015-01-21" default-to="2015-01-29" display-time="true"  ></ods-timerange>  shows two date fields.

Thanks

**Comment by jmorel** [comment]
Hello,

Not currently no. Timerange allows for the specification of a start-end date/time but doesn't has a mode for selecting a single date.

**Comment by fpassaniti** [comment]
In addition, you are free to hide the end date with CSS and force the end date value to 'now'.
We already did it for a project, it works well.
