### ISSUE TITLE
does it exist a callback from the widget

### ISSUE THREAD

**Issue by yaca29** [opendatasoft/ods-widgets#94]
Hi,

We try to do a carousel using a table with any items to display.

But we have an issue, because we don't know when the request it's done.

Does it exist a call back variable from the tag ods-result-enumerator ?

kindly

yann

**Comment by Amli** [comment]
There is currently no callback on this widget but you probably want to use the odsResults widget that should give you a bit more control over the results.

**Comment by yaca29** [comment]
thanks for the answer.
in fact, we will try with a json feed
