### ISSUE TITLE
odsRecordImage : what is the record's parameter ?

### ISSUE THREAD

**Issue by yaca29** [opendatasoft/ods-widgets#95]
hi,

have you a example of this directive ? i don't understand the record's parameter.

http://opendatasoft.github.io/ods-widgets/docs/#/api/ods-widgets.directive:odsRecordImage

kindy

yann

**Comment by Amli** [comment]
Hi,

the record is a representation of each individual line in the object resulting from a search query.
You can get a record by using something lke this:
```
    <ods-dataset-context context="tree" tree-dataset="arbresremarquablesparis2011" tree-domain="parisdata.opendatasoft.com" tree-parameters="{'sort': '-objectid'}">
        <div ods-results="records" ods-results-context="tree" ods-results-max="10">
            Total number of trees : {{ records.nhits }}
            <p ng-repeat="record in records">
                  {{ record }}
            </p>
        </div>
    </ods-catalog-context>
```
