### ISSUE TITLE
odsFilterSummary seems don't works

### ISSUE THREAD

**Issue by yaca29** [opendatasoft/ods-widgets#96]
hi,

I've a issue with odsFilterSummary directive.

in reference documention it's said that we can add a button "clear all" (http://opendatasoft.github.io/ods-widgets/docs/#/api/ods-widgets.directive:odsFilterSummary)

I add this directive in this example : http://widgets.caradec.fr/devenir4.php but it don't work 

<ods-filter-summary
     context="etab"
     clear-all-button="true">
</ods-filter-summary>

but, without the directive -> http://widgets.caradec.fr/devenir3.php t's work but there is no button.

It is a bug, or a mistake from me ? 

If it's works, is it possible to have the french translation of "clear all" ?

kindly

yann

**Comment by jmorel** [comment]
Hello,

It seems you're using an older version of Angular. The current version of ods-widgets relies on Angular 1.4+ whereas you're using angular 1.2. 

Here are the links to the relevant angular version.

``` html
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.7/angular.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.7/angular-sanitize.min.js"></script>```

This should solve your error (a dependency error).

**Comment by yaca29** [comment]
hi,
i change the version of angular, but there's still a error :
http://widgets.caradec.fr/devenir5.php -> angular.js:12477 Error: [$injector:unpr] Unknown provider: aProvider <- a
kindly

**Comment by jmorel** [comment]
Hello,

We indeed had a dependency injection issue with the minified version of the widgets. It's now fixed with a new release.

Your page now works as expected !

**Comment by yaca29** [comment]
Hi,
Thanks for the release, it's works 
Kindly 
Yann
