### ISSUE TITLE
Test if an ODS item is empty

### ISSUE THREAD

**Issue by itkg-asepchat** [opendatasoft/ods-widgets#98]
Hello all,

I'm using an **ods-result-enumerator** Widget to receive my data and display it in a Smarty page like that :
```
<span class="theme"'>
{literal}{{item.fields.thematiques}}{/literal}
</span>
```
       
It's working but I need to **test if my field is empty** before display it, how could I do that please ?

**Comment by richterb** [comment]
Hello,

You have access to AngularJS's standard tools, so you could use `ng-if` to display something depending on a condition.

For example
```html
<span ng-if="item.fields.thematiques">Thématiques : {{item.fields.thematiques}}</span>
```

**Comment by itkg-asepchat** [comment]
Thanks !
